version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/backend:${BACKEND_VERSION}
    container_name: sausage-store-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store
  backend-reportbackend-report:
    build:
      context: backend-report
      dockerfile: Dockerfile
    #image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/backend-report:${BACKEND_REPORT_VERSION}
    container_name: sausage-store-backend-report
    environment:
      DB: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/frontend:${FRONTEND_VERSION}
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: 