version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/sausage-backend:${BACKEND_VERSION}
    restart: 
      on-failure:5
    container_name: sausage-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store
  backend-report:
    # build:
    #   context: backend-report
    #   dockerfile: Dockerfile
    image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/backend-report:${BACKEND_REPORT_VERSION}
    restart: 
      on-failure:5
    container_name: sausage-backend-report
    environment:
      DB: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/sausage-frontend:${FRONTEND_VERSION}
    restart: 
      on-failure:5
    container_name: sausage-frontend
    ports:
      - "8080:80"
    networks:
      - sausage-store

networks:
  sausage-store: 