include:
  - template: Security/SAST.gitlab-ci.yml

stages: 
  - build  #сборка
  - test #test
  - notify  #уведомление
  - release
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия
  JAVA_OPTS: -XX:MaxRAMPercentage=90 # для того, чтобы Maven не съел всю свободную оперативку

build-backend-code-job: #задача с именем build-backend-code-job
  stage: build  #этап build
  only: 
    changes:
    - backend/**/* #только для изменений в директории backend
  script:
    - cd backend
    - "mvn package -Dspring.flyway.enabled=false -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Dversion.application=${VERSION}" # добавил еще 2 параметра сюда
    - echo "PREV_JOB_ID=${CI_JOB_ID}" >> ${CI_PROJECT_DIR}/build.env #доавил тут ci_project_dir
  #  - ls -lah - выполнял проверки, дебаг
  #  - pwd - выполнял проверки, дебаг
  #  - echo "The BACK_CI_JOB_ID is ${CI_PROJECT_DIR}" - проверка, что записано в переменную
  artifacts:
    paths:
      - backend/target/sausage-store-${VERSION}.jar  #сохранение собранного бэкенда как артефакта 
    expire_in: 1 day # указал срок хранения для артефакта
    reports:
      dotenv: ${CI_PROJECT_DIR}/build.env   #добавил тут переменную CI_PROJECT_DIR, так как на пердыдущем шаге записал переменную в директорию CI_PROJECT_DIR
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository



spotbugs-sast:  #задача с именем spotbugs-sast
  variables: 
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local 
  stage: test
  script: pwd
  needs: 
    - build-backend-code-job
    



sonarqube-backend-sast:
  variables: 
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  stage: test
  image: maven:3.8-openjdk-16 #образ
  script:
    - cd backend
    - "mvn --batch-mode verify sonar:sonar 
    -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
    -Dsonar.projectName=${SONAR_PROJECT_NAME_BACKEND} 
    -Dsonar.host.url=${SONARQUBE_URLBACKEND} 
    -Dsonar.login=${SONAR_LOGIN_BACKEND}
    -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
    -Dsonar.qualitygate.wait=true" #параметры
  needs:
    - build-backend-code-job




telegram-notification-backend: #задача с именем telegram-notification-backend
  variables:
      TEXT: "Андрей Николаев собрал backend ${CI_PROJECT_URL}/-/jobs/${PREV_JOB_ID}/artifacts/download" #обьявление перменных, где ci_project_url - урл проекта, prev_job_id - переменная, обявленная в джобе build-backend-code-job и сохраненная в {CI_PROJECT_DIR}/build.env
      TLGRM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify #этап уведомлений
  only:
    changes:
    - backend/* #только для изменений в директории backend
    variables: #РАСКОМЕНТИТЬ НЕ ЗАБУДЬ ЭТУ СТРОКУ И СЛЕДУЮЩУЮ!!!!!!!!!!!!
    - $CI_COMMIT_MESSAGE =~ /send notification/ # только для изменений содержащих в сообщении коммита "send notification"
  script:
     # - echo "The BACK_CI_JOB_ID is ${CI_PROJECT_DIR}" - проверки, при помощи которых опредлял CI_PROJECT_DIR
     # - echo "The BACK_CI_JOB_ID is $PREV_JOB_ID" - проверки, при помощи которых я определял, что записано в переменную prev_job_id
      - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002134018008\", \"text\": \"${TEXT}\" }" ${TLGRM}' #отправка курлом сообщения методом post
     # - ls -lah - дополнительные проверки
     # - pwd - дополнительные проверки
  needs:
    - build-backend-code-job # прописываем зависимость от джоба с именем build-backend-code-job
#добавил изменения для проверки

upload-backend-release:
  stage: release
  only:
    changes:
      - backend/**/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - "mvn deploy -DskipTests
   -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
   -s settings.xml -Dversion.application=${VERSION}"


backend-deploy:
  stage: deploy
  environment:
    name: staging
    url: http://std-024-12.praktikum-services.tech/ 
  before_script:
    #устанавливаем ssh-agent для удобства аутентификации по ssh
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s) #запускаем ssh агент для текущей оболчки
    #сохраняем сгенеренный ранее приватный ключ для раннера
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - #добавление приватного ключа
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
     #добавляем шаг копирования unit-файла:
    - scp ./backend/backend.service ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/backend.service #Этак команда отрабатывает первой на шаге деплоя
    #Этот фрагмент кода описывает процесс передачи файла "backend.service" с текущего компьютера на удаленный компьютер, используя указанные переменные для определения пользователя и пути сохранения.
    - ssh ${DEV_USER}@${DEV_HOST} "export "CURRENT_VERSION=${VERSION}"; export "VERSION=${VERSION}"; export "DEV_HOST=${DEV_HOST}";export "NEXUS_REPO_URL=${NEXUS_REPO_URL}"; export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"; export "NEXUS_REPO_BACKEND_NAME=${NEXUS_REPO_BACKEND_NAME}"; export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}";setsid /bin/bash -s " < ./backend/deploy.sh
    #В данном случае, мы экспортируем несколько переменных, которые будут использоваться в дальнейшем процессе. 
    #Затем мы запускаем фоновый процесс bash, который будет выполнять скрипт deploy.sh, расположенный в директории backend. Это скрипт для развертывания приложения на сервере
     # скачиваем ранее собранный артефакт с Nexus. При этом необходимо заранее
     # прописать креды от Nexus в переменные в настройке пайплайна
    #следующий шаг у нас перенесен в deploy.sh - "curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} -o sausage-store-${VERSION}.jar ${NEXUS_REPO_URL}/${NEXUS_REPO_BACKEND_NAME}/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar"
    # запускаем бэкенд  
    # этот шаг тоже перенесен в deploy.sh - java -jar sausage-store-${VERSION}.jar & 
