stages:
  - build
  - notify
  
build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  script:
    - ls -lah
    - pwd
    - cd backend
    - mvn package
    - echo "PREV_JOB_ID=${CI_JOB_ID}" >> ${CI_PROJECT_DIR}/build.env #доавил тут ci_project_dir
    - ls -lah
    - pwd
    - echo "The BACK_CI_JOB_ID is ${CI_PROJECT_DIR}"
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    expire_in: 1 day
    reports:
      dotenv: ${CI_PROJECT_DIR}/build.env   #добавил тут переменную посмотрим как отреагирует на нее CI_PROJECT_DIR
    


telegram-notification-backend:
  variables:
      TEXT: "Андрей Николаев собрал backend ${CI_PROJECT_URL}/-/jobs/${PREV_JOB_ID}/artifacts/download"
      TLGRM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify
  only:
    changes:
    - backend/*
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
      - ls -lah
      - pwd
      - echo "The BACK_CI_JOB_ID is ${CI_PROJECT_DIR}"
      - echo "The BACK_CI_JOB_ID is $PREV_JOB_ID"
      - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002134018008\", \"text\": \"${TEXT}\" }" ${TLGRM}'
      - ls -lah
      - pwd
  needs:
    - build-backend-code-job
#коммент
