---
apiVersion: apps/v1
kind: Deployment # тип сущности
metadata: # метаданные
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-024-12/sausage-store2/sausage-backend:latest
          imagePullPolicy: Always # image извлекается всегда
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: std-024-12
            - name: SPRING_DATASOURCE_PASSWORD
              value: Testusr1234
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rc1d-6ltxi07qdaaunpa5.mdb.yandexcloud.net:6432/std-024-12?ssl=true
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://std-024-12:Testusr1234@rc1d-fmpc8y27lrcif391.mdb.yandexcloud.net:27018/std-024-12?tls=true
            - name: SPRING_FLYWAY_BASELINE-ON-MIGRATE
              value: "true"

          # env:
          #   - name: VAULT_HOST
          #     value: 51.250.8.146
          #   - name: VAULT_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: vault
          #         key: vault_token
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
       - name: docker-config-secret # Чтобы получить образ из частного реестра, Kubernetes необходимы учетные данные. Поле imagePullSecretsв файле конфигурации указывает, что Kubernetes должен получить учетные данные из секрета с именем docker-config-secret
