apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF5TkMweE1qcEZOV2d6ZURsWWF3PT0iCgkJfQoJfQp9

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
data:
  SPRING_DATASOURCE_USERNAME: c3RkLTAyNC0xMgo=
  SPRING_DATASOURCE_PASSWORD: VGVzdHVzcjEyMzQK
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxZC02bHR4aTA3cWRhYXVucGE1Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDI0LTEyP3NzbD10cnVlCg==
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3N0ZC0wMjQtMTI6VGVzdHVzcjEyMzRAcmMxZC1mbXBjOHkyN2xyY2lmMzkxLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAyNC0xMj90bHM9dHJ1ZQo=
type: kubernetes.io/Basic-auth