apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF5TkMweE1qcEZOV2d6ZURsWWF3PT0iCgkJfQoJfQp9

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
data:
  DB: bW9uZ29kYjovL3N0ZC0wMjQtMTI6VGVzdHVzcjEyMzRAcmMxZC1mbXBjOHkyN2xyY2lmMzkxLm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAyNC0xMj90bHM9dHJ1ZSZ0bHNDQUZpbGU9L2FwcC9DQS5wZW0K
type: kubernetes.io/Basic-auth